services:
  - type: web
    name: governance-service
    env: docker
    rootDir: backend/governance-service
    region: oregon
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: 10000
