"""Add tr_versions table

Revision ID: 278dbe3a3b69
Revises: 15cd9405e901
Create Date: 2025-10-31 02:59:15.253856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278dbe3a3b69'
down_revision = '15cd9405e901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tr_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tr_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filetype', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tr_id'], ['trs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tr_versions_id'), 'tr_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tr_versions_id'), table_name='tr_versions')
    op.drop_table('tr_versions')
    # ### end Alembic commands ###
