"""Update ETP model

Revision ID: 2b937c20666e
Revises: ed06352c1659
Create Date: 2025-11-02 12:51:48.996061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b937c20666e'
down_revision: Union[str, None] = 'ed06352c1659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etps', 'step', new_column_name='current_step')
    op.alter_column('etps', 'created_by', new_column_name='created_by_id', existing_type=sa.VARCHAR(), type_=postgresql.UUID(as_uuid=True), postgresql_using='created_by_id::uuid')
    op.create_foreign_key(None, 'etps', 'users', ['created_by_id'], ['id'])
    op.create_unique_constraint(None, 'etps', ['edocs_number'])
    op.create_index(op.f('ix_etps_created_by_id'), 'etps', ['created_by_id'], unique=False)
    op.drop_index('ix_etps_created_by', table_name='etps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('etps', 'current_step', new_column_name='step')
    op.drop_constraint(None, 'etps', type_='foreignkey')
    op.drop_constraint(None, 'etps', type_='unique')
    op.drop_index(op.f('ix_etps_created_by_id'), table_name='etps')
    op.alter_column('etps', 'created_by_id', new_column_name='created_by', existing_type=postgresql.UUID(as_uuid=True), type_=sa.VARCHAR())
    op.create_index('ix_etps_created_by', 'etps', ['created_by'], unique=False)
    # ### end Alembic commands ###
