"""Add estimated_value, responsible_department, and priority to plans table

Revision ID: 2ff5506e16a1
Revises: 509881a9c29c
Create Date: 2025-10-27 02:56:30.523986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff5506e16a1'
down_revision: Union[str, None] = '509881a9c29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plans', sa.Column('responsible_department', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'priority')
    op.drop_column('plans', 'responsible_department')
    op.drop_column('plans', 'estimated_value')
    # ### end Alembic commands ###
