"""Add SignedDocument model and ETP signed status

Revision ID: 319e88565073
Revises: ea12505f9924
Create Date: 2025-11-01 02:01:34.195744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '319e88565073'
down_revision = 'ea12505f9924'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signed_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('etp', 'tr', name='documenttype'), nullable=False),
    sa.Column('signed_by_id', sa.String(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("ALTER TYPE etpstatus ADD VALUE 'signed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signed_documents')
    # ### end Alembic commands ###
    # NOTE: Removing a value from an ENUM is not directly supported in a transaction.
    # It requires creating a new type and migrating the data.
    # For this downgrade, we'll accept that the 'signed' value remains in the enum.
    pass