"""Add created_at to plans table

Revision ID: 509881a9c29c
Revises: cefbf4c73ff4
Create Date: 2025-10-27 01:21:07.414546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '509881a9c29c'
down_revision: Union[str, None] = 'cefbf4c73ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plannings_id', table_name='plannings')
    op.drop_table('plannings')
    op.add_column('plans', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'created_at')
    op.create_table('plannings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('market_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('necessity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solution_comparison', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contract_quantities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('technical_viability', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expected_results', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='plannings_pkey')
    )
    op.create_index('ix_plannings_id', 'plannings', ['id'], unique=False)
    # ### end Alembic commands ###
