"""Add ETP table

Revision ID: 6bdf84fa93e4
Revises:
Create Date: 2025-10-29 06:04:48.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bdf84fa93e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('edocs_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='etpstatus'), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etps_created_by', 'etps', ['created_by'], unique=False)
    op.create_index('ix_etps_edocs_number', 'etps', ['edocs_number'], unique=False)
    op.create_index('ix_etps_status', 'etps', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_etps_status', table_name='etps')
    op.drop_index('ix_etps_edocs_number', table_name='etps')
    op.drop_index('ix_etps_created_by', table_name='etps')
    op.drop_table('etps')
    # ### end Alembic commands ###
