"""Add ETP table

Revision ID: 6e0ca7f4bcf7
Revises: 9b85406c3347
Create Date: 2025-10-30 08:45:37.296525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0ca7f4bcf7'
down_revision: Union[str, None] = '9b85406c3347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='etpstatus'), nullable=True),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edocs', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edocs')
    )
    op.create_index(op.f('ix_etp_created_at'), 'etp', ['created_at'], unique=False)
    op.create_index(op.f('ix_etp_org_id'), 'etp', ['org_id'], unique=False)
    op.create_index(op.f('ix_etp_process_id'), 'etp', ['process_id'], unique=False)
    op.create_index(op.f('ix_etp_status'), 'etp', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etp_status'), table_name='etp')
    op.drop_index(op.f('ix_etp_process_id'), table_name='etp')
    op.drop_index(op.f('ix_etp_org_id'), table_name='etp')
    op.drop_index(op.f('ix_etp_created_at'), table_name='etp')
    op.drop_table('etp')
    op.execute('DROP TYPE etpstatus;')
    # ### end Alembic commands ###
