"""Add etp_validations table

Revision ID: b2961d306fab
Revises:
Create Date: 2025-10-29 15:58:39.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2961d306fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etp_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etp_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('error', 'warning', 'info', name='severity'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('suggestion', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etp_validations_id'), 'etp_validations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etp_validations_id'), table_name='etp_validations')
    op.drop_table('etp_validations')
    sa.Enum(name='severity').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
