"""Add trs table

Revision ID: c13b130deab3
Revises: 16fba41f2a0a
Create Date: 2025-10-30 00:18:55.894474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c13b130deab3'
down_revision: Union[str, None] = '16fba41f2a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('etp_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('BEM', 'SERVICO', name='trtype'), nullable=False),
    sa.Column('edocs_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='trstatus'), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trs_created_by'), 'trs', ['created_by'], unique=False)
    op.create_index(op.f('ix_trs_edocs_number'), 'trs', ['edocs_number'], unique=False)
    op.create_index(op.f('ix_trs_status'), 'trs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trs_status'), table_name='trs')
    op.drop_index(op.f('ix_trs_edocs_number'), table_name='trs')
    op.drop_index(op.f('ix_trs_created_by'), table_name='trs')
    op.drop_table('trs')
    op.execute("DROP TYPE trtype")
    op.execute("DROP TYPE trstatus")
    # ### end Alembic commands ###
