"""Add plan table

Revision ID: cefbf4c73ff4
Revises: 18da9927838e
Create Date: 2025-10-26 11:17:00.636761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cefbf4c73ff4'
down_revision: Union[str, None] = '18da9927838e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_objective'), 'plans', ['objective'], unique=False)
    op.create_index(op.f('ix_plans_justification'), 'plans', ['justification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_justification'), table_name='plans')
    op.drop_index(op.f('ix_plans_objective'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
