"""Add etp_ai_traces table

Revision ID: e83329e8903e
Revises: 3bbf6e3d9d1a
Create Date: 2025-10-29 14:50:22.223205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e83329e8903e'
down_revision: Union[str, None] = '3bbf6e3d9d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates_institucionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('tipo_contratacao', sa.String(length=100), nullable=True),
    sa.Column('versao', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('estrutura', sa.JSON(), nullable=False),
    sa.Column('mapeamento_campos', sa.JSON(), nullable=False),
    sa.Column('configuracao_documento', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_institucionais_id'), 'templates_institucionais', ['id'], unique=False)
    op.create_index(op.f('ix_templates_institucionais_instituicao_id'), 'templates_institucionais', ['instituicao_id'], unique=False)
    op.create_index(op.f('ix_templates_institucionais_tipo_contratacao'), 'templates_institucionais', ['tipo_contratacao'], unique=False)
    op.create_index(op.f('ix_templates_institucionais_tipo_documento'), 'templates_institucionais', ['tipo_documento'], unique=False)
    op.create_table('documentos_etp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('dados', sa.JSON(), nullable=False),
    sa.Column('campos_obrigatorios_preenchidos', sa.JSON(), nullable=False),
    sa.Column('progresso_percentual', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('campos_gerados_ia', sa.JSON(), nullable=True),
    sa.Column('scores_confianca_ia', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates_institucionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_etp_created_by'), 'documentos_etp', ['created_by'], unique=False)
    op.create_index(op.f('ix_documentos_etp_id'), 'documentos_etp', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_etp_plan_id'), 'documentos_etp', ['plan_id'], unique=False)
    op.create_index(op.f('ix_documentos_etp_status'), 'documentos_etp', ['status'], unique=False)
    op.create_table('etp_ai_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etp_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['etp_id'], ['documentos_etp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etp_ai_traces_etp_id'), 'etp_ai_traces', ['etp_id'], unique=False)
    op.create_index(op.f('ix_etp_ai_traces_id'), 'etp_ai_traces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etp_ai_traces_id'), table_name='etp_ai_traces')
    op.drop_index(op.f('ix_etp_ai_traces_etp_id'), table_name='etp_ai_traces')
    op.drop_table('etp_ai_traces')
    op.drop_index(op.f('ix_documentos_etp_status'), table_name='documentos_etp')
    op.drop_index(op.f('ix_documentos_etp_plan_id'), table_name='documentos_etp')
    op.drop_index(op.f('ix_documentos_etp_id'), table_name='documentos_etp')
    op.drop_index(op.f('ix_documentos_etp_created_by'), table_name='documentos_etp')
    op.drop_table('documentos_etp')
    op.drop_index(op.f('ix_templates_institucionais_tipo_documento'), table_name='templates_institucionais')
    op.drop_index(op.f('ix_templates_institucionais_tipo_contratacao'), table_name='templates_institucionais')
    op.drop_index(op.f('ix_templates_institucionais_instituicao_id'), table_name='templates_institucionais')
    op.drop_index(op.f('ix_templates_institucionais_id'), table_name='templates_institucionais')
    op.drop_table('templates_institucionais')
    # ### end Alembic commands ###
