"""Add etp_consolidation_jobs table

Revision ID: ec918fa3321a
Revises:
Create Date: 2025-10-31 23:29:27.785431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec918fa3321a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etp_consolidation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etp_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=True),
    sa.Column('checksum_sha1', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etp_id'], ['etp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etp_consolidation_jobs_etp_id'), 'etp_consolidation_jobs', ['etp_id'], unique=False)
    op.create_index(op.f('ix_etp_consolidation_jobs_job_id'), 'etp_consolidation_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etp_consolidation_jobs_job_id'), table_name='etp_consolidation_jobs')
    op.drop_index(op.f('ix_etp_consolidation_jobs_etp_id'), table_name='etp_consolidation_jobs')
    op.drop_table('etp_consolidation_jobs')
    # ### end Alembic commands ###
