"""Add Template model and link to TR

Revision ID: ee76c21eeefe
Revises: 8a865f8cc4c4
Create Date: 2025-11-01 00:21:32.078775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'ee76c21eeefe'
down_revision: Union[str, None] = '8a865f8cc4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('trs', sa.Column('template_id', UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'trs', 'templates', ['template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trs', type_='foreignkey')
    op.drop_column('trs', 'template_id')
    op.drop_table('templates')
    # ### end Alembic commands ###
