"""Add ETP workflow history table and update ETP model

Revision ID: fed64938ac57
Revises: 16fba41f2a0a
Create Date: 2025-10-31 18:42:52.483984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fed64938ac57'
down_revision: Union[str, None] = '16fba41f2a0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etp_workflow_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('etp_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etp_id'], ['etps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('etps', sa.Column('current_approver_id', sa.String(), nullable=True))
    op.add_column('etps', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.execute("ALTER TYPE etpstatus ADD VALUE 'in_review'")
    op.execute("ALTER TYPE etpstatus ADD VALUE 'approved'")
    op.execute("ALTER TYPE etpstatus ADD VALUE 'rejected'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etps', 'current_approver_id')
    op.drop_table('etp_workflow_history')
    op.execute("ALTER TYPE etpstatus RENAME TO etpstatus_old")
    op.execute("CREATE TYPE etpstatus AS ENUM('draft', 'published', 'archived')")
    op.execute((
        "ALTER TABLE etps ALTER COLUMN status TYPE etpstatus USING "
        "status::text::etpstatus"
    ))
    op.execute("DROP TYPE etpstatus_old")
    # ### end Alembic commands ###
