"""Create market_prices table

Revision ID: 1b2c3d4e5f6a
Revises:
Create Date: 2025-10-23 08:41:30.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2c3d4e5f6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_description', sa.Text(), nullable=False),
                    sa.Column('unit_value', sa.Numeric(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('purchase_date', sa.Date(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_market_prices_id'),
                    'market_prices', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
