name: CD Backend - governance-service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/governance-service/**'

jobs:
  deploy-to-eks:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-ECR-Role
          aws-region: us-east-1

      - name: Set up Kubeconfig for EKS
        uses: aws-actions/amazon-eks-kubeconfig@v1
        with:
          role-to-assume: ${{ secrets.AWS_EKS_KUBECTL_ROLE_ARN }} # Placeholder for a role that can access EKS
          cluster-name: nexora-comprasgov-cluster

      - name: Update image tag in Kubernetes manifest
        run: |
          IMAGE_TAG=${{ github.sha }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY=nexora-governance-service

          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" backend/governance-service/k8s/deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f backend/governance-service/k8s/deployment.yaml
          kubectl apply -f backend/governance-service/k8s/service.yaml
          kubectl apply -f backend/governance-service/k8s/ingress.yaml
