name: CD Backend - governance-service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/governance-service/**'

jobs:
  trigger-render-deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.RENDER_DEPLOY_HOOK != '' }}

    steps:
      - name: Trigger Render deployment
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
