name: CI Backend - governance-service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/governance-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/governance-service/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify seeding script path
        run: test -f backend/governance-service/app/scripts/create_user.py || (echo "Seeding script not found at the expected path" && exit 1)

      - name: Build Docker image for validation
        run: docker build . -f backend/governance-service/Dockerfile
