name: CI Backend - planning-service

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/planning-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/planning-service/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::266519201491:role/GitHubAction-ECR-Role
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nexora-planning-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./backend/planning-service
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
